# Site settings
title: Ronald Manganaro CV
description: Ronald Manganaro's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ronaldmanganaro.github.io/resumecard
url: https://ronaldmanganaro.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ronald Manganaro
  title: Software Developer
  address: Massachusetts, Woburn
  email: ronaldmanganaro@gmail.com
  link: http://ronaldmanganaro.github.io
  weibo:
  github: ronaldmanganaro
  linkedin: ronald-manganaro-58218378
  facebook: ronald.manganaro.1
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: University of Massachusetts Lowell
      location: Lowell, Massachusetts
      degree: Bachelor's of Science
      major: Computer Science<br>GPA 3.3
      started: 2014
      duration: (2014 - 2016)
      description: <h5>Relevant Course Work<h5> <table><tr><td><ul><li>Computing I, II, III, IV</li></ul></td><td><ul><li>Logic Design</li></ul></td></tr> <tr><td><ul><li>Assembly Language</li></ul></td><td><ul><li>Computer Architecture</li></ul></td></tr> </table>
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  programmingSkills:
    - skill1:
      name: C
      percentage: 100%
    - skill2:
      name: C++
      percentage: 100%
    - skill3:
      name: Java
      percentage: 70%
    - skill4:
      name: C#
      percentage: 70%
    - skill5:
      name: HTML/CSS/JavaScript
      percentage: 50%
