# Site settings
title: Ronald Manganaro CV
description: Ronald Manganaro's CV
favicon: /assets/img/avatar.JPG
baseurl: https://ronaldmanganaro.github.io/resumecard
url: https://ronaldmanganaro.github.io/resumecard
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ronald Manganaro
  title: Software Developer
  address: Massachusetts, Woburn
  email: ronaldmanganaro@gmail.com
  link: http://ronaldmanganaro.github.io
  weibo:
  github: ronaldmanganaro
  linkedin: ronald-manganaro-58218378
  facebook: ronald.manganaro.1
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Wii U Independent Developer
      location: Woburn, Massachusetts
      title: C# Developer
      started: 2016
      duration: (2016 - Present)
      description: <ul><li>Programmed in C#</li><li>Used the Unity3d game engine</li><li>Lead a team consisting of an artist, programmer, and musician</li></ul>
    - work2:
      company: University of Massachusetts Lowell
      location: Lowell, Massachusetts
      title: Computing II&#58; Data Structures Teaching Assistant
      started: 2015
      duration: (Sept 2015 - Dec 2015)
      description: <ul><li>Aided professor by grading quizzes and programming assignments</li><li>Answered questions the students had about course material and homework assignments</li><li>Made suggestions on how to improve or fix submitted assignments</li></ul>
    - work3:
      company: Citizens Disability
      location: Waltham, Massachusetts
      title: Supervisor of Client Services
      started: 2013
      duration: (May 2013 - August 2013)
      description: <ul><li>Made sure coworkers worked up to company standards</li><li>Organaized data through the use of spreadsheets and word documents</li></ul>
  educationHistory:
    - education1:
      organization: University of Massachusetts Lowell
      location: Lowell, Massachusetts
      degree: Bachelor's of Science
      major: Computer Science<br>GPA 3.3
      started: 2014
      duration: (2014 - 2016)
      description: <h5>Relevant Course Work</h5> <table><tr><td><ul><li>Computing I, II, III, IV</li></ul></td><td><ul><li>Logic Design</li></ul></td></tr> <tr><td><ul><li>Assembly Language</li></ul></td><td><ul><li>Computer Architecture</li></ul></td></tr> <tr><td><ul><li>Discrete Structures I, II</li></ul></td><td><ul><li>Calculus I, II</li></ul></td></tr> <tr><td><ul><li>Oral &amp; Written Communication for CS</li></ul></td><td><ul><li>Foundations of Computation</li></ul></td></tr> <tr><td><ul><li>Operating Systems</li></ul></td><td><ul><li>Software Engineering</li></ul></td></tr> <tr><td><ul><li>Ubiquiteous Computing</li></ul></td><td><ul><li>Android Development</li></ul></td></tr></table>
    - education2:
      organization: Middlesex Community College
      location: Bedford, Massachusetts
      degree: Bachelor's of Science
      major: Paralegal Studies<br>GPA 3.4
      started: 2011
      duration: (2011 - 2013)
  languages:
    - language1:
      name: Windows/Linux/Android OS
      proficiency: Expert
    - language2:
      name: Android Studio/Visual Studio/Bash
      proficiency: Intermediate
    - language3:
      name: Unity3d game Development tool
      proficiency: Intermediate
  programmingSkills:
    - skill1:
      name: C
      percentage: 100%
    - skill2:
      name: C++
      percentage: 100%
    - skill3:
      name: Java
      percentage: 70%
    - skill4:
      name: C#
      percentage: 70%
    - skill5:
      name: HTML/CSS/JavaScript
      percentage: 50%
